### PR TITLE
If extra argument is a function

### PR DESCRIPTION
**Pull request by mCzolko**
If we are able to pass extraArgument I'd like to extend it for function feature.
I'm solving case that I'd like to have api as a 3rd parameter. The issue is that I need to set up api configuration beforehand with possibility to access the state.

I'll show you an example:

```js
const createApi = (dispatch, getState) => {
  const { accessToken, refreshToken } = getState()

  const accessTokenChanged = (changedAccessToken) => {
    dispatch({ type: 'TOKEN_CHANGED', changedAccessToken })
  }

  return new Api({ accessToken, refreshToken, accessTokenChanged })
}
```

And the usage:

```js
const action = (dispatch, getState, api) =>
  api
    .getItems()
    .catch(error => dispatch({ type: 'GET_ITEMS_FAILED', error }))
    .then(items => dispatch({ type: 'GET_ITEMS_SUCCESS', items }))
```

Let me know if this makes sense, if it is a good solution. If yes, I'll add docs and tests.

### CODE REVIEW

**Comment by laat** [comment]
related: #232  #113 #85

**Comment by timdorr** [comment]
I've resisted this in the past, but it can't hurt. Can you please add tests and typing updates to this PR?

**Comment by laat** [comment]
It might be something we want to do, but it is a breaking change. The following code will break. 

```ts
const store = createStore(
  reducer,
  applyMiddleware(thunk.withExtraArgument(window.fetch))
);
const action = () => async (dispatch, getState, fetch) => {
  const apiKey = getState().apiKey;
  dispatch({ type: "fetch-started" });
  const response = await fetch("http://url", {
    headers: { "X-API-KEY": apiKey }
  });
  dispatch({ type: "fetch-complete", payload: await response.json() });
};

dispatch(action())
```

**Comment by timdorr** [comment]
Yeah, that's no good. Sorry, but I'm going to once again say no to this. If you need that kind of functionality, write your own middleware.

**Comment by laat** [comment]
For completeness, the original example provided could possibly be written like this:

```ts
const createApi = (dispatch, getState) => {
  const { accessToken, refreshToken } = getState();

  const accessTokenChanged = changedAccessToken => {
    dispatch({ type: "TOKEN_CHANGED", changedAccessToken });
  };

  return new Api({ accessToken, refreshToken, accessTokenChanged });
};

const action = (dispatch, getState) =>
  dispatch(createApi)
    .then(api => api.getItems())
    .then(items => dispatch({ type: "GET_ITEMS_SUCCESS", items }));
    .catch(error => dispatch({ type: "GET_ITEMS_FAILED", error }))
```

**Comment by mCzolko** [comment]
Thanks @laat for the example! I'll do it this way, you're right

**Comment by jessepinho** [comment]
FWIW @laat / @mCzolko , putting non-serializable values into the Redux store violates [one of the "essential" rules in the Redux style guide](https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions).

I'm solving this problem by making `extraArgument` an object outside of the store definition, then passing it into the store, then mutating `extraArgument` to bind my API function to the store. Not pretty, but it works:

```TS
const extraArgument = {}

const store = configureStore({
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware({
      thunk: {
        extraArgument,
      },
    }),
})

extraArgument.sendRequest = sendRequest.bind(store)
```

Then, inside `sendRequest`, you can access `getState`/`dispatch` via `this`:

```TS
function sendRequest(this: typeof store) {
  console.log('sendRequest', Object.keys(this)) // `sendRequest ["dispatch", "subscribe", "getState", "replaceReducer", "@@observable"]
`
}
```

**Comment by jessepinho** [comment]
Another option: create a higher-order function that wraps your thunk function:


```TypeScript
import { GetThunkAPI } from '@reduxjs/toolkit/dist/createAsyncThunk'
import { PayloadAction, ThunkDispatch } from '@reduxjs/toolkit'

import getSendRequest from './getSendRequest'
import { RootState } from '..'

type ThunkApi = GetThunkAPI<{
  state: RootState
  extra: { setterApi: typeof setterApi }
  dispatch: ThunkDispatch<
    RootState,
    { foo: 'your extra arg goes here' },
    PayloadAction<unknown>
  >
}>

/**
 * Use this to provide `sendRequest` to your thunk function.
 *
 * Normally, you would use `thunkApi.extra` to get whatever values you passed in
 * as the `extraArgument` to `configureStore`. However, our API needs access to
 * `dispatch` and `getState`, which are not available to `thunkApi.extra`. (See
 * https://github.com/reduxjs/redux-thunk/pull/274.) So, we have to use this
 * function to get `sendRequest` instead.
 *
 * @example
 *
 * ```TypeScript
 * const getPoints = createAsyncThunk(
 *   'points/getPoints',
 *   withSendRequest(async (sendRequest, userId: string) => {
 *     const response = await sendRequest('getPoints', { userId })
 *     return response
 *   }),
 * )
 * ```
 */
export default function withSendRequest<ThunkArg = void, ReturnValue = void>(
  action: (
    sendRequest: ReturnType<typeof getSendRequest>,
    thunkArg: ThunkArg,
    thunkApi: ThunkApi,
  ) => ReturnValue,
) {
  return (thunkArg: ThunkArg, thunkApi: ThunkApi) => {
    const sendRequest = getSendRequest(thunkApi.dispatch, thunkApi.getState)

    return action(sendRequest, thunkArg, thunkApi)
  }
}
```

`getSendRequest` looks like this:

```TypeScript
import reduxStore from '..'

export default function getSendRequest(
  dispatch: typeof reduxStore.dispatch,
  getState: typeof reduxStore.getState,
) {
  return function sendRequest(
    ...args
  ) {
    return fetch(..., { headers: { Authorization: `Bearer ${getState().auth.accessToken}` } })
  }
}

```

**Pull request closed without merging**
