### PR TITLE
Add Expo and React Native examples to CI

### PR DESCRIPTION
**Pull request by aryaemami59**
**This PR**:

  - [X] Adds Expo and React Native examples to CI workflow.

Depends on #364

### CODE REVIEW

**Comment by timdorr** [comment]
Honestly, this may be a bit of overkill for a 43 line, 1 file library 🙂

**Comment by timdorr** [comment]
This adds another 9-10 minute test onto the suite. I appreciate the completeness, but that seems like total overkill. I'm closing this one out. Thanks nonetheless!

**Comment by aryaemami59** [comment]
@timdorr I should add the same `actions/cache` usage to the CI here as well right?

**Comment by timdorr** [comment]
Yeah, that helps a tiny bit with all the example build times.

Thanks!

**Comment by aryaemami59** [comment]
@timdorr Thank you!

**Pull request merged**
