### PR TITLE
Add Prettier

### PR DESCRIPTION
**Pull request by jedmao**
Uses the following libraries to make this repo more contributor-friendly:

- [Prettier](https://prettier.io/) 💅
- ~~[Making your repo Commitizen-friendly](http://commitizen.github.io/cz-cli/#making-your-repo-commitizen-friendly)~~
- ~~[Semantic Release](https://semantic-release.gitbook.io/semantic-release/)~~

## ~~Automatic npm/GitHub release~~ 📦 ⬆️ 

~~This PR (if merged into master) and any future PRs merged directly into master will trigger an npm & GitHub release + changelog. This is done via [`@jedmao/semantic-release-npm-github-config`](https://github.com/jedmao/semantic-release-npm-github-config), as mentioned in [Semantic Release Community Configurations](https://semantic-release.gitbook.io/semantic-release/extending/shareable-configurations-list#community-configurations).~~

~~This was done in an effort to make maintenance and releases less of a burden to maintainers.~~

😀 ❤️ 

## ~~Important!~~ 🚨 

~~Before merging this PR (if you so decide), [ensure](https://github.com/jedmao/semantic-release-npm-github-config#configuration) that the following **_secret_** environment variables are set in your [Travis-CI settings](https://travis-ci.org/reduxjs/redux-thunk/settings):~~

- ~~[`GH_TOKEN`](https://github.com/settings/tokens) with [`public_repo`](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) access.~~
- ~~[`NPM_TOKEN`](https://docs.npmjs.com/cli/token)~~

### CODE REVIEW

**Comment by markerikson** [comment]
I'll be honest and say I really am not fond of the "conventional commit" format.  Is this something of a drive-by PR, or was this discussed with @timdorr at some point?

**Comment by jedmao** [comment]
Drive-by 🚗 😆 

I noticed [a conventional commit](https://github.com/reduxjs/redux-thunk/commit/ffd8834d9d9ed9e7f057c622bfb08129f03cad2a) in the commit history is all. Happy to modify the PR as needed.

**Comment by jedmao** [comment]
Not sure how to automate the package versions w/o conventional commits though.

**Comment by jedmao** [comment]
Perhaps something like this? https://github.com/sindresorhus/np

**Comment by timdorr** [comment]
Yeah, can we break this out into individual PRs? Adding Prettier is definitely worth its own commit.

**Comment by jedmao** [comment]
Just removed anything related to semantic release or conventional commits.

**Comment by markerikson** [comment]
And yes, I myself use `np` for doing actual publishing.

**Comment by timdorr** [comment]
I prefer the handcrafted, vintage, artisanal `npm publish` approach myself

**Comment by timdorr** [comment]
Thanks for the quick turnaround! The inconsistent semis and quotes was bugging me 😄

**Comment by jedmao** [comment]
> And yes, I myself use `np` for doing actual publishing.

Speaking of publishing, it's been a year since redux-thunk's last release. When can I expect to get my hands on a published version of #260? I really need it to fix a TS hole in [Redux Starter Kit](https://redux-starter-kit.js.org/).

**Comment by timdorr** [comment]
I can poke at it soon. It may be Monday, as I'm occupied by Dragon Con this weekend.

**Comment by jedmao** [comment]
Thanks and let me know if you need any help with anything TypeScript related. I just saw https://github.com/reduxjs/redux/pull/3536.

**Comment by timdorr** [comment]
Actually, check out reduxjs/redux#3500 for the full details.

**Pull request merged**
