### PR TITLE
Update TypeScript to 5.4

### PR DESCRIPTION
**Pull request by aryaemami59**
### This PR:

  - [X] Bumps TypeScript version to 5.4.
  - [X] Adds TypeScript 5.4 to TypeScript versions to test against during CI.

### CODE REVIEW

**Comment by EskiMojo14** [comment]
tests are failing - looks like node version is too low for yarn?

**Comment by aryaemami59** [comment]
@EskiMojo14
> tests are failing - looks like node version is too low for yarn?

Looks like #364 needs to be merged first.

**Comment by timdorr** [comment]
Merging in!

**Comment by aryaemami59** [comment]
@timdorr Thank you!!!

**Pull request merged**
